### ISSUE TITLE
i get error 0 write ip: destination address required

### ISSUE THREAD

**Issue by phucvinh52** [JoseFeng/synflood#1]
Hello you,
I get error "0 write ip: destination address required" when i run this tools.
Thank for your tool

**Comment by adrianosela** [comment]
Did you find a fix?

**Comment by sailornet** [comment]
0 write ip 0.0.0.0: write: destination address required ,not functional

**Comment by sailornet** [comment]
I also got  "0 write ip 0.0.0.0: write: destination address required"

**Comment by sailornet** [comment]
linux

**Comment by sailornet** [comment]
> Did you find a fix?

i fix it,check sum psdheader format  and algorithm problem

**Comment by fengve** [comment]
> > Did you find a fix?
> 
> i fix it,check sum psdheader format and algorithm problem

帮我提交一下吧，3Q
需要修改
1：增加tcp伪头部用于 check sum
2：rawSocket.Write修改为syscall.Sendto
我是懒得弄它了
